# Generated by Django 2.2.4 on 2019-09-29 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pa', 'Paypal'), ('Cr', 'Credit Card'), ('Cp', 'Crypto'), ('P2P', 'P2P Token')], max_length=50)),
            ],
            options={
                'verbose_name': 'PaymentMethod',
                'verbose_name_plural': 'PaymentMethods',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
            },
        ),
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
            ],
            options={
                'verbose_name': 'SellerAddress',
                'verbose_name_plural': 'SellerAddresss',
            },
        ),
        migrations.CreateModel(
            name='EnergyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('supplier', models.CharField(max_length=500)),
                ('net_meter', models.CharField(max_length=50)),
                ('avg_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('payment_duration', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('Fi', 'Fixed'), ('In', 'Installment')], max_length=2)),
                ('price_kwh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.SellerAddress', verbose_name='Address')),
                ('energy_source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.EnergySource')),
                ('payment_method', models.ManyToManyField(to='seller.PaymentMethod', verbose_name='Payment Methods')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'EnergyDetail',
                'verbose_name_plural': 'EnergyDetails',
            },
        ),
    ]
