# Generated by Django 2.2.4 on 2019-09-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AlterField(
            model_name='energydetail',
            name='sell_percent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
